on:
  push:

jobs:

steps:
- uses: manleydev/butler-publish-itchio-action@master
  env:
    BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
    CHANNEL: windows
    ITCH_GAME: example-project
    ITCH_USER: username
    PACKAGE: build/windows
