on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        ITCH_GAME: hju-l
        ITCH_USER: nergnezor
        PACKAGE: web
        CHANNEL: html5